### ISSUE TITLE
MATLAB, Octave, Julia and FORTRAN icons

### ISSUE THREAD

**Issue by krishnakumarg1984** [kdungs/latex-fontmfizz#3]
Hi, 

Can you please consider providing icon fonts for the MATLAB, Octave, Julia and FORTRAN programming languages?

These are scientific computing tools and there is a highly likelihood of large overlap of the users of these languages with the LaTeX community.

**Comment by kdungs** [comment]
Hi man,

sounds like an excellent suggestion. The mfizz font itself is not my work, however. You'll have to go over to https://github.com/fizzed/font-mfizz and ask Joe to put them in. Then, I can update this package accordingly.

Cheers!

**Comment by krishnakumarg1984** [comment]
@kdungs thanks! But the `README.md` for that repo clearly says that new icons nead pull-requests due to time commitments needed from the original package author.  An outstanding issue for the `julia` language icon already exists to which the project owner asks the community to make the icon and submit a PR. A recipe for doing this has been given.

I am too new to this sort of thing and scared of doing stuff incorrectly.   Can you perhaps give a go at making the `matlab` icon, and I can follow your lead shortly thereafter?

**Comment by kdungs** [comment]
Maybe my original reply was not clear enough. I don't make the icons. :) All I did was write a little script that builds them into a LaTeX package.

> I am too new to this sort of thing and scared of doing stuff incorrectly. Can you perhaps give a go at making the `matlab` icon, and I can follow your lead shortly thereafter?

Don't be scared to do it incorrectly. In the worst case, people will give you feedback on your PR and you can improve.

If nobody responds or your PR doesn't get in for other reasons that you disagree with, you can always make your own fork.
